### ISSUE TITLE
Add the dev repo authentication functionality for uv

### ISSUE THREAD

**Issue by meliz19** [TechnologyBrewery/habushu#312]
## Description
The purpose of this ticket is to add the private repo authentication functionality for uv, similar to what we already have in place for Poetry. 

## DoD
- [x] Add the private repo authentication functionality for uv
- [x] Add example project for adding dependencies from private repo for uv  
- [x] Update README docs

## Test Steps
- `mvn clean install -Pbootstrap`
- `mvn clean install`
- Remove the following lines from ` examples/uv/habushu-uv-publish-to-dev-repo/pyproject.toml`.
```toml
# Added by habushu-maven-plugin at 2025-04-07T17:01:47.037212 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.uv.index]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
priority = "supplemental"
```
- Follow the *Example Setup* instructions in the module's `README.md`. Set the private repo password to `password`. 

- Run `mvn clean deploy -Pdeploy-example`
- Verify the build fails with the following error message
```bash
Your credentials for private-repo must be set in your ~/.m2/settings.xml or you must export UV_INDEX_PRIVATE_REPO_USERNAME and UV_INDEX_PRIVATE_REPO_PASSWORD manually via the command line with the appropriate credentials. Visit the Publish to Development Repository and Install from Development Repository uv examples for additional configuration details. -> [Help 1]
```

- Follow the *Save your Development Repository Credentials in Maven*  instructions in the module's `README.md`. 
- Run `mvn clean deploy -Pdeploy-example`
- Verify the build is successful and the following lines are present in the logs
```
[INFO] Publishing to dev repository (useDevRepository=true, dev version being published)
[INFO] Publishing archives to http://127.0.0.1:8080/
```

- Remove the following lines from ` examples/uv/habushu-uv-install-from-dev-repo/pyproject.toml`.
```toml
# Added by habushu-maven-plugin at 2025-04-08T11:49:55.619435 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.uv.index]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
priority = "supplemental"
```
- Uncomment the dependency on line 11 in`examples/uv/habushu-uv-install-from-dev-repo/pyproject.toml`.
- Run `mvn clean install`
- Verify the build fails with the following error:
```bash
[WARNING] uv lock --check failed (debug contains more details) - this is likely due to a mismatch between your pyproject.toml and uv.lock file or missing uv.lock file. - attempting to correct...
[INFO] Executing uv command: uv lock
[ERROR]   × No solution found when resolving dependencies:
  ╰─▶ Because habushu-uv-publish-to-dev-repo was not found in the package
      registry and your project depends on habushu-uv-publish-to-dev-repo, we
      can conclude that your project's requirements are unsatisfiable.
```

- Run `mvn clean install -Pinstall-example`
- Verify a successful build and the following lines in the log
```bash
[INFO] Locking dependencies specified in pyproject.toml...
[INFO] Temporarily setting UV_INDEX_PRIVATE_REPO_USERNAME and UV_INDEX_PRIVATE_REPO_PASSWORD for use in uv command.
```

- Remove the server configs for the private-repo in your `~/.m2/settings.xml`
- Delete the `examples/uv/habushu-uv-install-from-dev-repo/uv.lock`
- Run `mvn clean install`
- Verify the build fails with the following error message
```bash
[INFO] Executing uv command: uv lock
[ERROR]   × No solution found when resolving dependencies:
  ╰─▶ Because habushu-uv-publish-to-dev-repo was not found in the package
      registry and your project depends on habushu-uv-publish-to-dev-repo, we
      can conclude that your project's requirements are unsatisfiable.

      hint: An index URL (http://127.0.0.1:8080/simple/) could not be queried
      due to a lack of valid authentication credentials (401 Unauthorized).
```

- Run `export UV_INDEX_PRIVATE_REPO_USERNAME=myuser && export UV_INDEX_PRIVATE_REPO_PASSWORD=password`
- Run `mvn clean install`
- Verify a successful build and the following lines in the log statement
- Comment out the dependency on line 11 in `examples/uv/habushu-uv-install-from-dev-repo/pyproject.toml`.
- Run `uv sync`
- Uncomment the dependency on line 11 in `examples/uv/habushu-uv-install-from-dev-repo/pyproject.toml`.
- Run `mvn clean install`
- Verify a successful build and the following line in the log
```bash
[INFO]  + habushu-uv-publish-to-dev-repo==3.0.0.dev1744114278
```
## Findings
- I can update the uv commands to use an environment variable like we have in the method: `executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables)`. This will work; however, when users try to run the same command, e.g., `uv lock`, in their command line, it will not work because the environment variables aren't persisted in the user's environment.
  - Do we think this is okay in this situation or should we just tell users to manually export these commands themselves, so the uv commands work the same whether they're run via the user manually or via maven? 
  - I'm inclined to suggest the latter option.
  - I spoke with @jaebchoi & @woods-cpointe and we decided to go with the `executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables)` option and let users know that habushu sets the environment variable before calling the method. 
- From the research I've done, it looks like you can't directly set a global environment variable with Java like you can in Python
- uv might add something like `uv config http-basic.repo-id username password` similar to Poetry in the future, but it might be a long ways off: https://github.com/astral-sh/uv/issues/8810.  
- uv appears to be cache
