### ISSUE TITLE
Support Baton-drive automatic migrations, apply to monorepo dependencies moving into the `[tool.poetry.group.monorepo.dependencies]` group

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#62]
Integrate Baton so we can perform common migration implictly.

Specifically, configure migrating monorepo dependencies moving into the `[tool.poetry.group.monorepo.dependencies]` group as the first Baton migration.

**Comment by d-ryan-ashcraft** [comment]
### Test Steps
 * Check out habushu project at https://github.com/TechnologyBrewery/habushu
 * Run `mvn clean install -Pbootstrap`
    * Verify that all unit tests passed successfully (newly added BDD specification `monorepo-migrations.feature` is included, so this validated functionality in an automated fashion)
 * Update `habushu/habushu-mixology-consumer/pyproject.toml` as follows:
     * Comment out the following lines (add the `#` to the front):
     ```toml
     #[tool.poetry.group.monorepo.dependencies]
     #habushu-mixology = {path = "../habushu-mixology", develop = true} 
     ```
    * Run `mvn clean install -pl :habushu-mixology-consumer`
    * Validate that `pyproject.toml` has no further changes 
* Update `habushu/habushu-mixology-consumer/pyproject.toml` as follows:
    * Move the `habushu-mixology` dependency to the `[tool.poetry.dependencies]` group:
     ```toml
     [tool.poetry.dependencies]
     python = "^3.11"
     habushu-mixology = {path = "../habushu-mixology", develop = true} 
     ```
    * Validate that `pyproject.toml` has a new `[tool.poetry.group.monorepo.dependencies]` that now contains the `habushu-mixology` dependency:
     ```toml
     [tool.poetry.dependencies]
     python = "^3.11"
     
     [tool.poetry.group.monorepo.dependencies]
     habushu-mixology = {path = "../habushu-mixology", develop = true}
     ```
* Do not `habushu/habushu-mixology-consumer/pyproject.toml` to verify that if the toml file is already in a desired state, no changes are made:
    * Run `mvn clean install -pl :habushu-mixology-consumer`
    * Validate that `pyproject.toml` has no further changes (monorepo group still exists with the same dependency)
* Update `habushu/habushu-mixology-consumer/pyproject.toml` as follows:
    * Move the `habushu-mixology` dependencies back to the `[tool.poetry.dependencies]`, but leave the now-empty group `[tool.poetry.group.monorepo.dependencies]` there:
     ```toml
     [tool.poetry.dependencies]
     python = "^3.11"
     habushu-mixology = {path = "../habushu-mixology", develop = true}
     
     [tool.poetry.group.monorepo.dependencies]
     ```
* Run `mvn clean install -pl :habushu-mixology-consumer`
* Validate that `pyproject.toml` has a new `[tool.poetry.group.monorepo.dependencies]` that now contains the `habushu-mixology` dependency:
     ```toml
     [tool.poetry.dependencies]
     python = "^3.11"
     
     [tool.poetry.group.monorepo.dependencies]
     habushu-mixology = {path = "../habushu-mixology", develop = true}
     ```
* Rollback your local changes to `habushu/habushu-mixology-consumer/pyproject.toml`
