### ISSUE TITLE
`poetry-core` migration breaks for projects not using major.minor.patch version references

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#76]
The recently added #66 automatically upgrade `poetry-core` versions to the minimum used by Habushu.  Unfortunately, it also breaks when the project's existing `pyproject.toml` file does not use a `major.minor.patch` versioning pattern.

For instance, the following `pyproject.toml` snippet will break the process:
```toml
[build-system]
requires = ["poetry-core>=1.6"]
build-backend = "poetry.core.masonry.api"
```

We should resolve this so any valid `poetry-core` version will be seamlessly upgraded.
